repos:
-   repo: https://github.com/lorenzwalthert/precommit
    rev: v0.3.2.9025
    hooks:
    -   id: use-tidy-description
        name: use-tidy-description
        description: run `usethis::use_tidy_description()`
        entry: Rscript inst/hooks/exported/use-tidy-description.R
        language: r
        files: '^DESCRIPTION$'
    -   id: style-files
        name: style-files
        description: style files with {styler}
        entry: Rscript inst/hooks/exported/style-files.R
        language: r
        files: '(\.[rR]profile|\.[rR]|\.[rR]md|\.[rR]nw|\.[qQ]md)$'
        exclude: 'renv/activate\.R'
        minimum_pre_commit_version: "2.13.0"
    -   id: lintr
        name: lintr
        description: check if a `.R` file is lint free (using {lintr})
        entry: Rscript inst/hooks/exported/lintr.R
        language: r
        files: '(\.[rR]profile|\.R|\.Rmd|\.Rnw|\.r|\.rmd|\.rnw)$'
        exclude: 'renv/activate\.R'
        minimum_pre_commit_version: "2.13.0"
